### PR TITLE
Create code to create a multisignature script

### PR DESCRIPTION
**Pull request by richarddushime**
Hi @448-OG 
I have created the  script in the  #8 issue 
i will need your review 
Thanks

### CODE REVIEW

**Comment by 448-OG** [comment]
As we said in the meeting, we are using bitcoin-cli instead

**Comment by richarddushime** [comment]
> As we said in the meeting, we are using bitcoin-cli instead

Great

**Comment by ItoroD** [comment]
so @richarddushime are you going to change that to bitcoin cli to do a multisig transaction?

**Comment by richarddushime** [comment]
> so @richarddushime are you going to change that to bitcoin cli to do a multisig transaction?

I m looking into that option too

**Pull request closed without merging**
